import streamlit as st

st.set_page_config(page_title="AI Recommendations - ChurnGuard", page_icon="💡", layout="wide")

# Top header / search row
col_title, col_search, col_actions = st.columns([2, 2, 1])
with col_title:
    st.markdown("## AI Recommendations")
    st.caption("Prioritized retention actions generated by AI — updated Dec 14, 2023")
with col_search:
    st.text_input("", placeholder="🔍 Search customers, tickets...", label_visibility="collapsed")
with col_actions:
    cols_btn = st.columns(2)
    with cols_btn[0]:
        st.button("🔄 Refresh")
    with cols_btn[1]:
        st.button("📥 Export Plan", use_container_width=True)

st.markdown("---")

# Metrics Cards row
m1, m2, m3 = st.columns(3)
with m1:
    st.metric(label="Customers Requiring Action", value="3", delta="High + Critical risk", delta_color="inverse")
with m2:
    st.metric(label="Est. Churn Reduction", value="-34%", delta="With full plan execution", delta_color="normal")
with m3:
    st.metric(label="Revenue Protected", value="$284K", delta="At-risk MRR this quarter", delta_color="normal")

st.markdown("<br>", unsafe_allow_html=True)

# Recommendation Card 1
with st.container(border=True):
    c_head1, c_head2 = st.columns([4, 1])
    with c_head1:
        st.markdown("### 🔴 DataStream Analytics")
        st.caption("Critical • Analytics • MRR $2,000")
    with c_head2:
        st.markdown("<div style='text-align: right; color: #EF4444; font-weight: bold;'>Churn Risk<br><span style='font-size: 24px;'>91%</span></div>", unsafe_allow_html=True)
    
    st.info("⚠️ 4 escalations in 30 days. Onboarding issues unresolved for 3 weeks. Extremely high churn probability.")
    
    b1, b2, b3, b4 = st.columns(4)
    with b1: st.button("👤 Assign Agent", key="btn_rec_1")
    with b2: st.button("🏷️ Send Offer", key="btn_rec_2")
    with b3: st.button("📅 Schedule Meeting", key="btn_rec_3")
    with b4: st.button("✉️ Generate Email", key="btn_rec_4")
    
    st.markdown("---")
    f_col1, f_col2 = st.columns([2, 2])
    f_col1.caption("Est. revenue at risk: **$24,000/yr**")
    f_col2.markdown("<div style='text-align: right; color: #10B981; font-size: 13px;'>Estimated churn reduction if acted: <b>-28%</b></div>", unsafe_allow_html=True)

# Recommendation Card 2
with st.container(border=True):
    c_head1, c_head2 = st.columns([4, 1])
    with c_head1:
        st.markdown("### 🔴 Acme Corporation")
        st.caption("Critical • Manufacturing • MRR $4,000")
    with c_head2:
        st.markdown("<div style='text-align: right; color: #EF4444; font-weight: bold;'>Churn Risk<br><span style='font-size: 24px;'>87%</span></div>", unsafe_allow_html=True)
    
    st.info("⚠️ High escalation rate with repeated billing complaints. 3 unresolved tickets in the past 30 days indicate serious dissatisfaction.")
    
    b1, b2, b3, b4 = st.columns(4)
    with b1: st.button("👤 Assign Agent", key="btn_rec_5")
    with b2: st.button("🏷️ Send Offer", key="btn_rec_6")
    with b3: st.button("📅 Schedule Meeting", key="btn_rec_7")
    with b4: st.button("✉️ Generate Email", key="btn_rec_8")
    
    st.markdown("---")
    f_col1, f_col2 = st.columns([2, 2])
    f_col1.caption("Est. revenue at risk: **$48,000/yr**")
    f_col2.markdown("<div style='text-align: right; color: #10B981; font-size: 13px;'>Estimated churn reduction if acted: <b>-28%</b></div>", unsafe_allow_html=True)