-- =====================================================
-- View: vw_revenue_by_region
-- Purpose:
-- Calculates revenue generated by each region.
-- Used By:
-- Revenue Dashboard
-- =====================================================

CREATE VIEW vw_revenue_by_region AS

SELECT

    c.region,

    COUNT(DISTINCT c.customer_id) AS total_customers,

    SUM(t.amount) AS total_revenue,

    AVG(t.amount) AS average_transaction

FROM customers c

JOIN transactions t

ON c.customer_id = t.customer_id

GROUP BY

    c.region;